name: Env Builder
author: lovneet
description: "Create .env file"
branding:
  icon: "file"
  color: purple
inputs:
  secrets:
    description: "Github Secrets"
    required: true
  variables:
    description: "Github Variables"
    required: true
  branch:
    description: "Branch Name"
    required: true
  extra:
    description: "Extra Variables"
    required: false
outputs:
  env:
    description: "processed env file"
runs:
  using: "node16"
  main: "dist/index.js"
